const TECHMAP_DEMO_TEMPLATES = [
  {
    id: 'wire-cutting',
    title: 'Резка провода',
    category: 'COAX',
    description: 'Подготовка заготовок кабеля RG58 по длине.',
    projectCode: '630K.1',
    operationHeader: 'Резка провода',
    assemblyName: 'Кабельная сборка BNC-Male to BNC-Male RG58 1m',
    tools: [
      { name: 'Набор шестигранников', qty: '1 шт' },
      { name: 'Электронный штангенциркуль', qty: '1 шт' },
    ],
    equipment: [{ name: 'Станок для нарезки провода', qty: '1 шт' }],
    materials: [{ name: 'RG58', qty: '15,3 м' }],
    steps: [
      'Убедиться в корректности используемого провода согласно КД.',
      'Настроить станок исходя из параметров используемого кабеля.',
      'Резать партиями по 50 шт и связывать в пучки.',
      'Если длина превышает 1 м - сматывать в бухты и резать по одному.',
      'Контролировать длину резки первых 10 шт после настройки и каждые 100 шт далее.',
      'Следить за дефектами реза и при необходимости останавливать операцию для корректировки.',
    ],
    results: [{ name: 'RG58 1020 мм', qty: '15' }],
    timings: [{ name: 'RG58 1020 мм', minutes: '6' }],
    footer: {
      header: ['Материал', 'Длина', 'мм', 'Кол-во', 'сек на одну', 'подготовка'],
      rows: [['RG58', '1020', 'мм', '15', '3', '300']],
    },
    imagePlaceholders: [
      { range: 'F6:J11', caption: 'Фото / схема настройки резки' },
      { range: 'F13:J20', caption: 'Критерии приемки реза' },
    ],
    images: [
      {
        url: 'https://dummyimage.com/420x180/eaf2ff/335/ffffff.png&text=Wire+cutting+setup',
        row: 6,
        column: 6,
        width: 320,
        height: 135,
        label: 'wire-cutting-setup',
      },
      {
        url: 'https://dummyimage.com/420x220/f8f8f8/555/ffffff.png&text=Cut+quality+reference',
        row: 13,
        column: 6,
        width: 320,
        height: 165,
        label: 'wire-cutting-quality',
      },
    ],
  },
  {
    id: 'linear-material-cutting',
    title: 'Резка линейных материалов',
    category: 'Материалы',
    description: 'Нарезка термоусадочной трубки и других линейных материалов.',
    projectCode: '630K.1',
    operationHeader: 'Резка линейных материалов',
    assemblyName: 'Кабельная сборка BNC-Male to BNC-Male RG58 1m',
    tools: [{ name: 'Набор шестигранников', qty: '1 шт' }],
    equipment: [{ name: 'Станок для нарезки линейных материалов', qty: '1 шт' }],
    materials: [{ name: 'ТУТ 6/3 мм, черная', qty: '0,6 м' }],
    steps: [
      'Поставить необходимые ножи для ровного реза.',
      'Выставить необходимую длину нарезаемого материала.',
      'Произвести тестовый рез и проверить длину и ровность края.',
    ],
    results: [{ name: 'ТУТ 6/3 мм, черная 20 мм', qty: '30' }],
    timings: [{ name: 'ТУТ 6/3 мм, черная 20 мм', minutes: '5' }],
    footer: {
      header: ['Материал', 'Длина', 'мм', 'Кол-во', 'Кол-во сторон', 'сек на одну', 'подготовка'],
      rows: [['ТУТ 6/3 мм, черная', '20', 'мм', '30', '2', '0,5', '300']],
    },
    imagePlaceholders: [
      { range: 'F6:J11', caption: 'Фото шаблона линейного материала' },
      { range: 'F13:J20', caption: 'Пример корректного торца после резки' },
    ],
    images: [
      {
        url: 'https://dummyimage.com/420x180/e8f5e9/2e7d32/ffffff.png&text=Linear+material+cutting',
        row: 6,
        column: 6,
        width: 320,
        height: 135,
        label: 'linear-cutting-main',
      },
      {
        url: 'https://dummyimage.com/420x220/fff3e0/ef6c00/ffffff.png&text=Tube+cut+result',
        row: 13,
        column: 6,
        width: 320,
        height: 165,
        label: 'linear-cutting-result',
      },
    ],
  },
  {
    id: 'coax-stripping',
    title: 'Зачистка провода (COAX)',
    category: 'COAX',
    description: 'Подготовка центральной жилы, диэлектрика и экрана под разъем.',
    projectCode: '630K.1',
    operationHeader: 'Зачистка провода (COAX)',
    assemblyName: 'Кабельная сборка BNC-Male to BNC-Male RG58 1m',
    tools: [{ name: 'Электронный штангенциркуль', qty: '1 шт' }],
    equipment: [{ name: 'Станок для зачистки коаксиалов', qty: '1 шт' }],
    materials: [
      { name: 'RG58 1020 мм', qty: '15' },
      { name: 'BNC-C58P', qty: '15' },
    ],
    steps: [
      'Изготовить станок под разъем по документации либо опытному образцу.',
      'Проверить корректность зачистки под используемый разъем и при расхождении скорректировать настройку.',
      'Зачищать подготовленными пучками по 50 шт, проверяя начало каждого пучка.',
    ],
    results: [
      { name: 'Зачистка A под BNC-C58P на кабеле RG58 1020 мм', qty: '15' },
      { name: 'Зачистка B под BNC-C58P на кабеле RG58 1020 мм', qty: '15' },
    ],
    timings: [
      { name: 'Зачистка A под BNC-C58P', minutes: '13' },
      { name: 'Зачистка B под BNC-C58P', minutes: '13' },
    ],
    footer: {
      header: ['Операция', 'Название разъема', 'Материал', 'Кол-во', 'сек на одну', 'подготовка'],
      rows: [
        ['Зачистка A', 'BNC-C58P', 'RG58 1020 мм', '15', '10', '600'],
        ['Зачистка B', 'BNC-C58P', 'RG58 1020 мм', '15', '10', '600'],
      ],
    },
    imagePlaceholders: [
      { range: 'F5:H9', caption: 'Эталон PASS 1' },
      { range: 'I5:K9', caption: 'Схема геометрии 1' },
      { range: 'F11:H15', caption: 'Эталон PASS 2' },
      { range: 'I11:K15', caption: 'Схема геометрии 2' },
      { range: 'I16:K22', caption: 'Фото NG / дефекты' },
    ],
    sideLabels: [
      { range: 'F23:H24', text: 'PASS', color: '#38761d' },
      { range: 'I23:K24', text: 'NG', color: '#cc0000' },
    ],
    images: [
      {
        url: 'https://dummyimage.com/280x120/eaf2ff/335/ffffff.png&text=PASS+strip+example+1',
        row: 5,
        column: 6,
        width: 210,
        height: 90,
        label: 'coax-strip-pass-1',
      },
      {
        url: 'https://dummyimage.com/280x120/fff3e0/ef6c00/ffffff.png&text=Strip+geometry+1',
        row: 5,
        column: 9,
        width: 210,
        height: 90,
        label: 'coax-strip-geometry-1',
      },
      {
        url: 'https://dummyimage.com/280x120/e8f5e9/2e7d32/ffffff.png&text=PASS+strip+example+2',
        row: 11,
        column: 6,
        width: 210,
        height: 90,
        label: 'coax-strip-pass-2',
      },
      {
        url: 'https://dummyimage.com/280x120/fce4ec/ad1457/ffffff.png&text=Strip+geometry+2',
        row: 11,
        column: 9,
        width: 210,
        height: 90,
        label: 'coax-strip-geometry-2',
      },
      {
        url: 'https://dummyimage.com/280x180/f8d7da/842029/ffffff.png&text=NG+defects',
        row: 16,
        column: 9,
        width: 210,
        height: 135,
        label: 'coax-strip-ng',
      },
    ],
  },
  {
    id: 'coax-pin-side-a',
    title: 'Монтаж пинов стороны A (COAX)',
    category: 'COAX',
    description: 'Подпайка центрального пина к центральной жиле коаксиала.',
    projectCode: '630K.1',
    operationHeader: 'Монтаж пинов стороны A',
    assemblyName: 'Кабельная сборка BNC-Male to BNC-Male RG58 1m',
    tools: [{ name: 'Перчатки защитные', qty: '1 шт' }],
    equipment: [
      { name: 'Паяльник', qty: '1 шт' },
      { name: 'Припой POS 63/61', qty: '1 шт' },
      { name: 'Флюс ORLO', qty: '1 шт' },
    ],
    materials: [
      { name: 'RG58 1020 мм', qty: '15' },
      { name: 'BNC-C58P (Пин)', qty: '15' },
    ],
    steps: [
      'Надеть защитные перчатки перед работой.',
      'Настроить паяльник на 230 градусов.',
      'Установить подходящее жало паяльника.',
      'Нанести флюс на центральную жилу коаксиала.',
      'Набрать необходимое количество припоя на жало.',
      'Припаять пин к центральной жиле коаксиала.',
    ],
    results: [{ name: 'Припаянный пин BNC-C58P к RG58 1020 мм', qty: '15' }],
    timings: [{ name: 'Припаивание пина BNC-C58P к RG58 1020 мм', minutes: '8' }],
    footer: {
      header: ['Операция', 'Разъем', 'Провод', 'шт', 'сек на одну', 'подготовка'],
      rows: [['Припаивание (пин)', 'BNC-C58P', 'RG58 1020 мм', '15', '25', '120']],
    },
    imagePlaceholders: [
      { range: 'F5:H9', caption: 'Фото до пайки' },
      { range: 'I5:K9', caption: 'Установка пина' },
      { range: 'F11:H15', caption: 'Эталон PASS' },
      { range: 'I11:K15', caption: 'Эталон NG' },
    ],
    sideLabels: [
      { range: 'F22:H23', text: 'PASS', color: '#38761d' },
      { range: 'I22:K23', text: 'NG', color: '#cc0000' },
    ],
    images: [
      {
        url: 'https://dummyimage.com/280x120/eaf2ff/335/ffffff.png&text=Pin+before+soldering',
        row: 5,
        column: 6,
        width: 210,
        height: 90,
        label: 'pin-before',
      },
      {
        url: 'https://dummyimage.com/280x120/fff3e0/ef6c00/ffffff.png&text=Pin+installation',
        row: 5,
        column: 9,
        width: 210,
        height: 90,
        label: 'pin-installation',
      },
      {
        url: 'https://dummyimage.com/280x120/e8f5e9/2e7d32/ffffff.png&text=PASS+solder',
        row: 11,
        column: 6,
        width: 210,
        height: 90,
        label: 'pin-pass',
      },
      {
        url: 'https://dummyimage.com/280x120/f8d7da/842029/ffffff.png&text=NG+solder',
        row: 11,
        column: 9,
        width: 210,
        height: 90,
        label: 'pin-ng',
      },
    ],
  },
  {
    id: 'coax-connector-side-a',
    title: 'Монтаж коннектора стороны A (COAX)',
    category: 'COAX',
    description: 'Опрессовка корпуса разъема и монтаж термоусадки.',
    projectCode: '630K.1',
    operationHeader: 'Монтаж коннектора стороны A (COAX)',
    assemblyName: 'Кабельная сборка BNC-Male to BNC-Male RG58 1m',
    tools: [{ name: 'Набор шестигранников', qty: '1 шт' }],
    equipment: [
      { name: 'Станок опрессовки', qty: '1 шт' },
      { name: 'Матрицы с маркировкой (X)', qty: '1 шт' },
    ],
    materials: [
      { name: 'ТУТ 6/3 мм, черная 20 мм', qty: '15' },
      { name: '(Гильза) BNC-C58P', qty: '15' },
      { name: '(Корпус) BNC-C58P', qty: '15' },
      { name: 'Припаянные (пин) BNC-C58P к RG58 1020 мм', qty: '15' },
    ],
    steps: [
      'Надеть защитные перчатки перед работой.',
      'Установить матрицы с маркировкой (X) на пресс.',
      'Надеть ТУТ 6/3 мм, черная 20 мм.',
      'Надеть гильзу BNC-C58P.',
      'Установить разъем по datasheet.',
      'Опрессовать корпус BNC-C58P.',
      'Термоусадить ТУТ 6/3 мм, черная 20 мм поверх гильзы.',
    ],
    results: [{ name: 'BNC-C58P RG58 1020 мм - open end', qty: '15' }],
    timings: [{ name: 'BNC-C58P RG58 1020 мм - open end', minutes: '20' }],
    footer: {
      header: ['Операция', 'Материал', 'шт', 'сек на одну', 'подготовка'],
      rows: [
        ['Установить матрицы на пресс', 'Матрицы с маркировкой', '15', '40', '600'],
        ['Надеть', 'ТУТ 6/3 мм, черная 20 мм', '15', '', ''],
        ['Надеть', '(Гильза) BNC-C58P', '15', '', ''],
        ['Опрессовать', '(Корпус) BNC-C58P', '15', '', ''],
        ['Термоусадить', 'ТУТ 6/3 мм, черная 20 мм поверх гильзы', '15', '', ''],
      ],
    },
    imagePlaceholders: [
      { range: 'F6:H12', caption: 'PASS - внешний вид' },
      { range: 'I6:K12', caption: 'PASS - центральный пин' },
      { range: 'F14:H20', caption: 'NG - внешний вид' },
      { range: 'I14:K20', caption: 'NG - центральный пин' },
    ],
    sideLabels: [
      { range: 'L8:L11', text: 'PASS', color: '#38761d' },
      { range: 'L16:L19', text: 'NG', color: '#cc0000' },
    ],
    images: [
      {
        url: 'https://dummyimage.com/280x180/e8f5e9/2e7d32/ffffff.png&text=Connector+PASS+body',
        row: 6,
        column: 6,
        width: 210,
        height: 135,
        label: 'connector-pass-body',
      },
      {
        url: 'https://dummyimage.com/280x180/eaf2ff/335/ffffff.png&text=Connector+PASS+pin',
        row: 6,
        column: 9,
        width: 210,
        height: 135,
        label: 'connector-pass-pin',
      },
      {
        url: 'https://dummyimage.com/280x180/f8d7da/842029/ffffff.png&text=Connector+NG+body',
        row: 14,
        column: 6,
        width: 210,
        height: 135,
        label: 'connector-ng-body',
      },
      {
        url: 'https://dummyimage.com/280x180/fff3e0/ef6c00/ffffff.png&text=Connector+NG+pin',
        row: 14,
        column: 9,
        width: 210,
        height: 135,
        label: 'connector-ng-pin',
      },
    ],
  },
];
